- name: Install pass
  package:
    name: pass
    state: present
  become: "{{ ansible_os_family != 'Darwin' }}"

# Need to configure ssh forwarding
- name: Clone pass repository
  git:
    repo: 'git@github.com:kosciej16/pass.git'
    dest: $HOME/.password-store
    accept_hostkey: yes

# gpg --import private.asc is needed, however it asks interactively
# for a password and couldn't automate that
