--- #
- hosts: ubuntu
  vars:
    localDir: "{{ localRoot }}/khal"
  tasks:
    - name: Install pip
      package:
        name: python3-pip
        state: present
      become: yes

    - name: Install pipx
      pip:
        name: pipx

    - name: Install khal and dependencies
      block:
        - name: Install khal and dependencies
          shell: "pipx install {{ item }}"
          with_items: ["vdirsyncer", "git+git://github.com/pimutils/khal.git"]
          environment:
            PATH: "{{ ansible_env.PATH }}:.local/bin"

        - name: Install vdirsyncer lib
          shell: "pipx inject vdirsyncer requests-oauthlib"
          environment:
            PATH: "{{ ansible_env.PATH }}:.local/bin"

    - name: Copy configuration
      copy:
        src: "{{ localDir }}/{{ item }}"
        dest: "{{ configDir }}"
      with_items: [khal, vdirsyncer]

    - name: Copy aliases
      copy:
        src: "{{ localDir }}/"
        dest: "{{ aliasesDir }}/khal"

    - name: Add sourcing aliases
      blockinfile:
        path: ~/.profile
        block: |
          for c in ~/.aliases/* ; do
            . $c
          done

    - name: Systemd
      block:
        - name: Create user systemd directory
          file:
            path: "{{ configDir }}/systemd/user"
            state: directory

        - name: Copy systemd files
          copy:
            src: "{{ localDir }}/{{ item }}"
            dest: "{{ configDir }}/systemd/user/"
          with_items: [vdirsyncer.service, vdirsyncer.timer]

        # - name: Discover calendars
        #   shell: "vdirsyncer discover"
        #   environment:
        #     PATH: "{{ ansible_env.PATH }}:$HOME/.local/bin"

        - name: Enable vdirsyncer timer
          systemd:
            name: vdirsyncer.timer
            enabled: yes
            user: yes
            state: started
