- name: Install sxhkd
  package:
    name: sxhkd
    state: present
  become: "{{ ansible_os_family != 'Darwin' }}"

- name: Make sure config directory exists
  file:
    path: "{{ config_dir }}/sxhkd"
    state: directory

- name: Copy config files
  copy:
    src: sxhkdrc
    dest: "{{ config_dir }}/sxhkd"
