- name: Install skhd
  homebrew:
    name: skhd
    state: present

- name: Start skhd service
  command: brew services start skhd

- name: Make sure config directory exists
  file:
    path: "{{ config_dir }}/skhd"
    state: directory

- name: Copy config files
  copy:
    src: skhdrc
    dest: "{{ config_dir }}/skhd"
