- include_tasks: commons_linux.yml
  when:
    - ansible_facts['distribution'] == "Ubuntu"

- include_tasks: commons_mac.yml
  when:
    - ansible_facts['distribution'] == "MacOSX"

- name: Install pipx
  package:
    name: [pipx]
    state: present
  become: "{{ ansible_os_family != 'Darwin' }}"

- name: Add pipx binaries to PATH
  shell: pipx ensurepath
