- name: Copy dot files
  copy:
    src: "bashrc"
    dest: "$HOME/.bashrc"

- name: Copy aliases
  copy:
    src: "aliases"
    dest: "{{ aliases_dir }}/misc"

- name: Copy scripts
  copy:
    src: "bin/new_role"
    dest: "{{ scripts_dir }}/"
