- name: Install dunst
  import_tasks: roles/commons/tasks/install_with_make.yml
  vars:
    repo: https://github.com/dunst-project/dunst.git
    build_dep: true
    make_params: {WAYLAND: 0}

- name: Enable dunst service
  import_tasks: roles/commons/tasks/enable_service.yml
  vars:
    name: mbsync
    with_time: true

- name: Make sure config directory exists
  file:
    path: "{{ config_dir }}/dunst"
    state: directory

- name: Copy config files
  ansible.builtin.synchronize:
    src: "{{ role_path }}/files/"
    dest: "{{ config_dir }}/dunst"
    mode: push
    rsync_opts:
      - "--no-perms"
  delegate_to: localhost

