--- #
- hosts: ubuntu
  vars:
    mailDir: $HOME/.mail
    neomuttRepoDir: "{{ repoDir }}/neomutt"
    localDir: "{{ localRoot }}/neomutt"
    hostDir: "{{ configDir }}/neomutt"
  tasks:

    - name: pass
      block:
        - name: Install pass and dependencies
          package:
            name: [pass, rofi]
            state: present
          become: yes

        - name: Clone pass repository
          git:
            repo: 'git@github.com:kosciej16/pass.git'
            dest: $HOME/.password-store
            accept_hostkey: yes

        - name: Copy gnpug keys
          command: cp -Tr $HOME/.password-store/gnupg $HOME/.gnupg

        - name: Change .gnupg permissions
          file:
            path: $HOME/.gnupg
            state: directory
            mode: '0700'

        - name: Get gpg key id
          shell: (gpg -K | grep -A1 sec | tail -1)
          register: gpg_key_id

        - name: Init pass database
          shell: "pass init {{ gpg_key_id.stdout }}"


    - name: isync
      block:
      - name: Install isync
        package:
          name: isync
          state: present
        become: yes

      - name: Create mail directories
        file:
          state: directory
          path: "{{ mailDir }}/{{ item }}"
        with_items: [work, home]

      - name: Copy config
        copy:
          src: "{{ localDir }}/mbsync/mbsyncrc"
          dest: "$HOME/.mbsyncrc"

      - name: Sync emails
        command: mbsync -a

      - name: Systemd
        block:
          - name: Create user systemd directory
            file:
              path: "{{ configDir }}/systemd/user"
              state: directory

          - name: Copy systemd files
            copy:
              src: "{{ localDir }}/mbsync/{{ item }}"
              dest: "{{ configDir }}/systemd/user/"
            with_items: [mbsync.service, mbsync.timer]

          - name: Enable mbsync timer
            systemd:
              name: mbsync.timer
              enabled: yes
              user: yes
              state: started

    - name: msmtp
      block:
      - name: Copy msmtp config
        copy:
          src: "{{ localDir }}/msmtp/msmtprc"
          dest: "$HOME/.msmtprc"

    - name: notmuch
      block:
      - name: Install notmuch
        package:
          name: notmuch
          state: present
        become: yes

      - name: Copy notmuch hooks
        copy:
          src: "{{ localDir }}/notmuch/hooks"
          dest: "{{ mailDir }}/.notmuch/"
          mode: 0755

      - name: Copy notmuch config
        copy:
          src: "{{ localDir }}/notmuch/notmuch-config"
          dest: "$HOME/.notmuch-config"

      - name: Init notmuch database
        command: "notmuch new"
        chdir: "{{ mailDir }}"

    - name: Check if neomutt is installed
      shell: "which neomutt"
      register: result
      ignore_errors: true

    - name: neomutt
      block:
      - name: Clone neomutt repository
        git:
          repo: 'git@github.com:neomutt/neomutt.git'
          dest: "{{ repoDir }}/neomutt"

      # Some ansible problem
      # - apt_repository:
      #     repo: deb-src http://pl.archive.ubuntu.com/ubuntu/ focal universe
      #     state: present

      - name: Install neomutt dependencies
        apt:
          name: neomutt
          state: build-dep
        become: yes

      - name: Configure
        command: ./configure --notmuch
        args:
          chdir: "{{ neomuttRepoDir }}"

      - name: Make
        make:
          chdir: "{{ neomuttRepoDir }}"

      - name: Make install
        make:
          chdir: "$HOME/repos/neomutt"
          target: install
        become: yes
        become_user: "{{ ansible_ssh_user }}"

      - name: Copy neomutt configuration
        copy:
          src: "{{ localDir }}/neomutt/{{ item }}"
          dest: "{{ hostDir }}/"
        with_items: [bindings, colors, mailboxes, mailcap, muttrc, printing.sh]
      when: result.rc != 0
