- include_role:
    name: nvim

- name: Create coc extension directory
  file:
    state: directory
    path: "{{ config_dir }}/coc/extensions"

- name: Install Node
  block:
  - name: Install n
    import_tasks: roles/commons/tasks/install_with_curl.yml
    vars:
      name: n
      cmd: curl -L https://bit.ly/n-install | bash -s -- -y

  - name: Install Node with n
    ansible.builtin.command: "{{ local_bin_dir }}/n lts"
    become: yes

- name: Copy config file
  copy:
    src: "coc-settings.json"
    dest: "{{ config_dir }}/nvim/"
