- include_role:
    name: nvim

- name: Create coc extension directory
  file:
    state: directory
    path: "{{ config_dir }}/coc/extensions"

- name: Install node
  block:
  - name: Check if n is already installed
    ansible.builtin.stat:
      path: "$HOME/n"
    register: n_installed

  - name: Install n, the Node.js version manager
    ansible.builtin.shell:
      cmd: curl -L https://bit.ly/n-install | bash -s -- -y
    when: not n_installed.stat.exists

  - name: Add n to PATH
    lineinfile:
      path: ~/.profile
      line: "export PATH=$PATH:$HOME/n/bin"

- name: Copy config file
  copy:
    src: "coc-settings.json"
    dest: "{{ config_dir }}/nvim/"
