- name: Install isync
  package:
    name: isync
    state: present
  become: "{{ ansible_os_family != 'Darwin' }}"

- name: Create mail directories
  file:
    state: directory
    path: "{{ mail_dir }}/{{ item }}"
  with_items: [home, itsg, starfish]

- name: Copy config
  copy:
    src: "mbsyncrc"
    dest: "$HOME/.mbsyncrc"

- name: Enable mbsync service
  import_tasks: roles/commons/tasks/enable_service.yml
  vars:
    name: mbsync
    with_time: true
  when:
    - ansible_facts['distribution'] == "Ubuntu"

- name: Launchctl
  block:
    - name: Copy launchctl plist file
      copy:
        src: "mbsync.plist"
        dest: "~/Library/LaunchAgents/"

    - name: Load file
      shell: launchctl load ~/Library/LaunchAgents/mbsync.plist

    - name: Start file
      shell: launchctl start mbsync
    # - name: Doesnt work
    #   community.general.launchd:
    #     name: mbsync
    #     state: started
  when:
    - ansible_facts['distribution'] == "MacOSX"
