
# TODO Install from source?
# git clone https://github.com/tmux/tmux.git
# cd tmux
# sh autogen.sh
# ./configure
# make && sudo make install

- name: Install tmux
  package:
    name: tmux
    state: present
  become: "{{ ansible_os_family != 'Darwin' }}"

- name: Copy config files
  copy:
    src: "{{ item }}.conf"
    dest: "{{ tmux_config_dir }}/"
  with_items: [tmux, bindings, mouse_b, ressurect]

- name: Clone tmux plugin manager repository
  git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: "{{ tmux_config_dir }}/plugins/tpm"
