---
- name: Create basic files
  file:
    path: "{{ item }}"
    state: file
  with_items:
    - $HOME/.bashrc
    - $HOME/.profile

- name: Source files
  lineinfile:
    path: "$HOME/.bash_profile"
    line: "{{ item }}"
  with_items:
    - "[[ -e $HOME/.bashrc ]] && source $HOME/.bashrc"
    - "[[ -e $HOME/.profile ]] && source $HOME/.profile"
