- include_role:
    name: python_commons

- include_role:
    name: nvim

- name: Install apps with pipx
  shell: "pipx install {{ item }}"
  with_items: [pylint, ipdb, ruff]

- name: Install libs with pip
  pip:
    name: pdbpp

- name: Copy python configuration
  copy:
    src: "{{ item }}"
    dest: "$HOME/.{{ item }}"
  with_items:
    - pylintrc
    - pdbrc.py

- name: Setup python support
  pip:
    name: pynvim
    virtualenv: $HOME/pynvim
    virtualenv_command: "{{ ansible_python_interpreter }} -m venv"
