- name: Install git
  package:
    name: git
    state: present
  become: "{{ ansible_os_family != 'Darwin' }}"

- name: Copy config files
  copy:
    src: "{{ item }}"
    dest: "$HOME/.{{ item }}"
  with_items: [gitignore, gitconfig, gitconfig-sf]
