let g:pytest_executable = "pytest"
nnoremap <leader>ta :Pytest project<cr>
nnoremap <leader>tf :Pytest file<cr>
nnoremap <leader>tm :Pytest function<cr>
nnoremap <leader>ts :Pytest session<cr>
nnoremap <leader>te :Pytest error<cr>
nnoremap <leader>tl :Pytest fails<cr>
nnoremap <leader>tc :Pytest clear<cr>
nnoremap <leader>t1 :Pytest first<cr>
nnoremap <leader>t0 :Pytest last<cr>
nnoremap <leader>t] :Pytest next<cr>
nnoremap <leader>t[ :Pytest previous<cr>
