- name: Add Docker's official GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: 'a+r'

# TODO amd64 should be dpkg --print-architecture
- name: Add Docker repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    create: yes
    line: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Docker Engine
  ansible.builtin.apt:
    name: docker-ce, docker-ce-cli, containerd.io, docker-buildx-plugin, docker-compose-plugin
    state: present
    update_cache: yes

- name: Copy aliases
  copy:
    src: "docker"
    dest: "{{ aliases_dir }}/docker"
