---
- hosts: localhost
  roles:
    - mbsync
    - notmuch
    - msmtp
    # TODO It randomly deletes the email, need to switch to goimapnotify
    # - imapnotify
    - neomutt
    # TODO imapfilter?
