- name: Install taskwarrior
  package:
    name: taskwarrior
    state: present
  become: "{{ ansible_os_family != 'Darwin' }}"

- name: Copy aliases
  copy: 
    src: "aliases"
    dest: "{{ aliases_dir }}/taskwarrior"


