- name: Install taskwarrior
  package:
    name: taskwarrior
    state: present
  become: "{{ ansible_os_family != 'Darwin' }}"

- name: Copy aliases
  copy: 
    src: "taskwarrior"
    dest: "{{ aliases_dir }}/taskwarrior"

- name: Copy configs
  copy: 
    src: taskrc
    dest: "{{ ansible_env.HOME }}/.taskrc"

- name: Ensure .task directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.task"
    state: directory
    mode: '0755'

- name: Copy .task directory content
  ansible.builtin.copy: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    directory_mode: '0755'
  loop:
    - { src: "task/", dest: "{{ ansible_env.HOME }}/.task" }
  loop_control:
    label: "{{ item.src }}"
      
# TODO separate role?
- name: Install rust
  import_tasks: roles/commons/tasks/install_with_curl.yml
  vars:
    name: .rustup
    cmd: curl https://sh.rustup.rs -sSf | bash -s -- -y

- name: Clone taskwarrior tui repository
  git:
    repo: "https://github.com/kdheepak/taskwarrior-tui.git"
    dest: "{{ repo_dir }}/taskwarrior-tui"

- name: Install taskwarrior tui
  ansible.builtin.command: cargo build --release
  args:
    chdir: "{{ repo_dir }}/taskwarrior-tui"

- name: "Create symlink to taskwarrior-tui"
  file:
    src: "{{ repo_dir }}/taskwarrior-tui/target/release/taskwarrior-tui"
    dest: "{{ local_bin_dir }}/ttui"
    state: link
