- name: Install neomutt
  package:
    name: neomutt
    state: present
  when:
    - ansible_facts['distribution'] == "MacOSX"

- name: Install neomutt
  block:
  - name: Clone neomutt repository
    git:
      repo: 'https://github.com/neomutt/neomutt.git'
      dest: "{{ neomutt_repo_dir }}"

  - name: nazwa
    apt_repository:
      repo: deb-src http://pl.archive.ubuntu.com/ubuntu/ jammy universe
      state: present
    become: yes

  - name: Install neomutt dependencies
    apt:
      name: neomutt
      state: build-dep
    become: yes

  - name: Configure neomutt
    command: ./configure --notmuch
    args:
      chdir: "{{ neomutt_repo_dir }}"

  - name: Make
    make:
      chdir: "{{ neomutt_repo_dir }}"

  - name: Make install
    make:
      chdir: "{{ neomutt_repo_dir }}"
      target: install
    become: yes
  when:
    - ansible_facts['distribution'] == "Ubuntu"

- name: Install neomutt dependencies
  pip:
    name: urlscan

- name: Copy neomutt configuration
  copy:
    src: "{{ item }}"
    dest: "{{ config_dir }}/neomutt/"
  with_items: [bindings, colors, mailboxes, mailcap, muttrc, printing.sh, conf]
