- name: Install neomutt
  package:
    name: neomutt
    state: present
  when:
    - ansible_facts['distribution'] == "MacOSX"

- name: Install neomutt
  block:
  - name: Add apt repository with dependencies
    apt_repository:
      repo: "deb-src http://pl.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
      state: present
    become: yes

  - name: Install neomutt
    import_tasks: roles/commons/tasks/install_with_make.yml
    vars:
      repo: "https://github.com/neomutt/neomutt.git"
      configure_params: "--notmuch"
      build_dep: true
  when:
    - ansible_facts['distribution'] == "Ubuntu"

- name: Install neomutt dependencies
  pip:
    name: urlscan

- name: Copy neomutt configuration
  copy:
    src: "{{ item }}"
    dest: "{{ config_dir }}/neomutt/"
  with_items: [bindings, colors, mailboxes, mailcap, muttrc, printing.sh, conf]
